### ISSUE TITLE
Create instance action

### ISSUE THREAD

**Issue by duncancasemore** [ApplaudSolutions/Applaud-Workato-Connector#11]
## Summary

1. **As a** Integration Designer
1. **I want** to build recipes that create data in Applaud
1. **so that** I can integrate actions from other apps back into Applaud

## Acceptance Criteria

1. I can select the Create instance action
1. I can select the model.  This shows exactly the same set of models as the trigger actions (eg, #5)
1. When I select the model, I see this shows in lower case singular in the action title above and in the recipe viewer
1. When I select the model, I then see fields for all required model properties
1. I see that optional fields are collapsed show optional fields section
1. I see that fields are required or not based on the model property settings in Applaud
1. I don't see the Id field
1. I see the fields in the order of the property order specified in Applaud (not alphabetic)
1. I see that the field labels match the property titles used in Applaud
1. I see that Free-text properties show as text properties
1. I see that Number properties show as number properties
1. I see that Boolean properties show as boolean properties
1. I see that Date properties show as date properties
1. I see that Date/time properties show as date/time properties
1. I see that Date range properties show as complex objects with separate fields for Start and End.  I see that the Start and End fields are required or not dependent on whether the date range is required or not.
1. If I enter Start or End of a date range, I have to enter the other (one cannot be left blank)
1. I see that Date/time range properties show as complex objects with separate fields for Start date/time and End date/time.  I see that the Start date/time and End date/time fields are required or not dependent on whether the date/time range is required or not.
1. If I enter Start date/time or End date/time of a date/time range, I have to enter the other (one cannot be left blank)
1. I see that File properties show as a text property
1. I see that User properties show as a text property
1. I see that Email properties show as an email property
1. I see that URL properties show as a link property
1. I see that I can enter http://, https://, tel:, sms: and other URL structures rather than just fixed web links (if not this probably needs to be a text property; ideally the regex between Applaud & Workato match)
1. I see that Geopoint is a complex property that includes breakout number type fields for the Latitude and Longitude.  I see that the Lat and Lon fields are required or not dependent on whether the geopoint is required or not.
1. If I enter Lat or Lon of a geopoint, I have to enter the other (one cannot be left blank)
1. I see that lookup properties are a text type
1. I see that foreign key properties are a text type
1. I see that icon fields are a text type
1. I see that color fields are a color-picker type or, if that's not available, a simple text type
1. I see that when this action fires it creates the data in Applaud by using the POST action
1. I see that all model properties (including the id) are available to use in later recipe actions as datapills
1. I see that the created and last updated by data in Applaud clearly shows it's been updated by the API and that the timestamps are correct

### Create action
![Applaud action create.png](https://images.zenhubusercontent.com/555f40e64f7a08fbb7f2eb05/84cacc03-704b-4309-a294-1c374b271999)

## Notes

* Separate stories track autocomplete fields for user, lookup, foreign key and icon fields

## Developer Testing
_Requestor:_ leave this section blank
_Developer:_ complete this section during commit/pull request 

**Positive testing:**

Add all the things that you have checked whilst completing this story here, it should be written in a non-technical way, and a lot of this can probably be taken from the acceptance criteria, here are two different examples:  
- **I checked that** the language of the page changed to Spanish **when** I selected Spanish in the language dropdown  
- **I checked that** the list filtered correctly **when** I added an isBefore date filter on list block  

**Negative testing:** 

Here you list the things you have checked where your code needs to show an error, handle unusual/bad input/config gracefully, or may impact separate features that use or depend on the same code. Pause and think -- they may not be obvious!  Examples:    
- **I checked that** there was no "Select language" dropdown option **when** there is only one language configured
- **I checked that** a nice error is shown **when** a language is selected, but the page isn't translated into that language yet
- **I checked that** my list filter code changes didn't cause problems **when** filters are used in other places like ACLs, workflow if/then, and select list filters
- **I checked that** in list filters, I can only select a date type property for the "Value" field, **when** the "Property" field is a date type property

**e2e test links and description:**
- http://www.Link-to-Ghost-inspector-test.com - and paste the test description here
- http://www.Link-to-another-Ghost-inspector-test.com - and paste the test description here

**Comment by GangamRitesh** [comment]
### Status update

- [x] I can select the Create instance action
![image](https://user-images.githubusercontent.com/40355220/98661757-e1670f80-236c-11eb-8244-6aed2c0bf588.png)
- [x] I can select the model. This shows exactly the same set of models as the trigger actions
![image](https://user-images.githubusercontent.com/40355220/98664935-0198cd80-2371-11eb-9de3-724f0a3eb1fb.png)
- [x] When I select the model, I then see fields for all required model properties
- [x] I see that fields are required or not based on the model property settings in Applaud
- [x] I see that optional fields are collapsed show optional fields section
![image](https://user-images.githubusercontent.com/40355220/98662388-b335ff80-236d-11eb-879e-89cc81fa6e5a.png)
- [x] I don't see the Id field
![image](https://user-images.githubusercontent.com/40355220/98662438-c8129300-236d-11eb-8aae-6e4e5aabc9a9.png)
![image](https://user-images.githubusercontent.com/40355220/98662468-d3fe5500-236d-11eb-8d3e-4a71996927f6.png)
- [x] I see the fields in the order of the property order specified in Applaud (not alphabetic)
- [x] I see that the field labels match the property titles used in Applaud
- [x] I see that Free-text properties show as text properties
![image](https://user-images.githubusercontent.com/40355220/98662764-43744480-236e-11eb-9480-a00ce9a5a68d.png)

- [x] I see that Number properties show as number properties
![image](https://user-images.githubusercontent.com/40355220/98662825-57b84180-236e-11eb-9bfd-d69b83c6bff8.png)

- [x] I see that Date properties show as date properties
![image](https://user-images.githubusercontent.com/40355220/98662857-60a91300-236e-11eb-95f8-fd826ff09142.png)

- [x] I see that Date range properties show as complex objects with separate fields for Start and End. I see that the Start and End fields are required or not dependent on whether the date range is required or not.
![image](https://user-images.githubusercontent.com/40355220/98662958-79192d80-236e-11eb-9991-f4c740e0b1bf.png)


- [x] I see that File properties show as a text property
![image](https://user-images.githubusercontent.com/40355220/98663760-808d0680-236f-11eb-9788-31787cb06c48.png)

- [x] I see that User properties show as a text property
![image](https://user-images.githubusercontent.com/40355220/98663785-8682e780-236f-11eb-8a7f-91cb085a5cec.png)

- [x] I see that Email properties show as an email property
![image](https://user-images.githubusercontent.com/40355220/98663022-8fbf8480-236e-11eb-950d-507f31563888.png)

- [x] I see that URL properties show as a link property
![image](https://user-images.githubusercontent.com/40355220/98663053-96e69280-236e-11eb-92c2-0d3c33031780.png)

- [x] I see that Geopoint is a complex property that includes breakout number type fields for the Latitude and Longitude. I see that the Lat and Lon fields are required or not dependent on whether the geopoint is required or not.
![image](https://user-images.githubusercontent.com/40355220/98662977-80d8d200-236e-11eb-8ab0-2bc08126ba69.png)

- [x] I see that lookup properties are a text type
![image](https://user-images.githubusercontent.com/40355220/98663805-8e428c00-236f-11eb-858c-11c27b5984e0.png)

- [x] I see that foreign key properties are a text type
![image](https://user-images.githubusercontent.com/40355220/98663832-94d10380-236f-11eb-9b15-b9775ff1643a.png)

- [x] I see that icon fields are a text type
![image](https://user-images.githubusercontent.com/40355220/98663201-ca292180-236e-11eb-8cb2-ae70f732cb61.png)

- [x] I see that color fields are a color-picker type or, if that's not available, a simple text type.(As per documentation there is no color picker type. Need to check with workato team)
![image](https://user-images.githubusercontent.com/40355220/98663853-9bf81180-236f-11eb-81cd-7c5eb48b4c38.png)

- [x] I see that when this action fires it creates the data in Applaud by using the **POST** action

### Pending Items
- [ ] I see that Boolean properties show as boolean properties
- [ ] I see that Date/time properties show as date/time properties (need to test)
- [ ] If I enter Start or End of a date range, I have to enter the other (one cannot be left blank)
- [ ] I see that Date/time range properties show as complex objects with separate fields for Start date/time and End date/time. I see that the Start date/time and End date/time fields are required or not dependent on whether the date/time range is required or not.
- [ ] If I enter Start date/time or End date/time of a date/time range, I have to enter the other (one cannot be left blank)
- [ ] I see that I can enter http://, https://, tel:, sms: and other URL structures rather than just fixed web links (if not this probably needs to be a text property; ideally the regex between Applaud & Workato match)(need to work)
- [ ] If I enter Lat or Lon of a geopoint, I have to enter the other (one cannot be left blank)

- [ ] I see that all model properties (including the id) are available to use in later recipe actions as datapills.
- [ ] I see that the created and last updated by data in Applaud clearly shows it's been updated by the API and that the timestamps are correct.
