### ISSUE TITLE
Upsert instance action

### ISSUE THREAD

**Issue by duncancasemore** [ApplaudSolutions/Applaud-Workato-Connector#13]
## Summary

1. **As a** Integration Designer
1. **I want** to build recipes that either create or update data in Applaud
1. **so that** I can integrate actions from other apps back into Applaud

## Acceptance Criteria

1. I can select the Upsert instance action
1. I can select the model.  This has the same behavior as #11
1. When I select the model, I see this shows in lower case singular in the action title above and in the recipe viewer
1. When I select the model, I then see all the model property fields similar to #11.  Unlike update, required fields should show as required because they're needed for any created instances.
1. I see the Id field, which is the first one shown, is of text type and optional but 'sticky'
1. I see that when this action fires it updates the data in Applaud by using the PATCH action
1. I see that all model properties (including the id) are available to use in later recipe actions as datapills
1. I see that the last updated by data in Applaud clearly shows it's been updated by the API
1. I see that the last updated by date in Applaud reflects the correct date/time stamp
1. I see that the created date is unchanged

### Upsert action
![Applaud action upsert.png](https://images.zenhubusercontent.com/555f40e64f7a08fbb7f2eb05/4651ed01-0fb1-4469-a883-878c61e3eb01)

## Notes

None

## Developer Testing
_Requestor:_ leave this section blank
_Developer:_ complete this section during commit/pull request 

**Positive testing:**

Add all the things that you have checked whilst completing this story here, it should be written in a non-technical way, and a lot of this can probably be taken from the acceptance criteria, here are two different examples:  
- **I checked that** the language of the page changed to Spanish **when** I selected Spanish in the language dropdown  
- **I checked that** the list filtered correctly **when** I added an isBefore date filter on list block  

**Negative testing:** 

Here you list the things you have checked where your code needs to show an error, handle unusual/bad input/config gracefully, or may impact separate features that use or depend on the same code. Pause and think -- they may not be obvious!  Examples:    
- **I checked that** there was no "Select language" dropdown option **when** there is only one language configured
- **I checked that** a nice error is shown **when** a language is selected, but the page isn't translated into that language yet
- **I checked that** my list filter code changes didn't cause problems **when** filters are used in other places like ACLs, workflow if/then, and select list filters
- **I checked that** in list filters, I can only select a date type property for the "Value" field, **when** the "Property" field is a date type property

**e2e test links and description:**
- http://www.Link-to-Ghost-inspector-test.com - and paste the test description here
- http://www.Link-to-another-Ghost-inspector-test.com - and paste the test description here

**Comment by GangamRitesh** [comment]
HI @duncancasemore ,
Created upsert action as per wireframe.
In upsert if the record is to be updated, action is working as expected. If the action is create, action is throwing an error. 
As per wireframe id field is set as required field. But for creating an instance id value is passed as null. So, recipe is throwing an error. So Id cannot be set as required. There is an option to set this field as sticky, which means by default Id will be shown(not in optional fields), but this will not be first field.
### Error thrown when trying to create an instance through upsert action.
![image](https://user-images.githubusercontent.com/40355220/100572025-83d63b00-32fa-11eb-9815-ccd5492f1081.png)
### Id field is displayed after required fields(sticky = true , optional = true)
![image](https://user-images.githubusercontent.com/40355220/100574726-a8cdac80-3300-11eb-90c4-eedc175fbe5e.png)
Can you please review...

**Comment by duncancasemore** [comment]
@GangamRitesh good catch, I've updated AC5 based on your recommendation. Does this work?

**Comment by GangamRitesh** [comment]
@duncancasemore , required fields are shown first. Id field will not be the first one. Will check with workato team if Id can be displayed on top.

**Comment by GangamRitesh** [comment]
@duncancasemore ,
I have checked with Workato team. It is not possible to show Id field before required fields. Required fields will be shown on top, then follows fields that are optional fields (sticky).

**Comment by duncancasemore** [comment]
@GangamRitesh ok fine

**Comment by GangamRitesh** [comment]
- [x] 1. I can select the Upsert instance action
![image](https://user-images.githubusercontent.com/40355220/102993187-b6163980-4542-11eb-98b5-7e5ca19af407.png)

- [x] 1. I can select the model. 
![image](https://user-images.githubusercontent.com/40355220/102993212-c201fb80-4542-11eb-9319-8bd82d1f00ac.png)

- [x] 1. When I select the model, I see this shows in lower case singular in the action title above and in the recipe viewer
![image](https://user-images.githubusercontent.com/40355220/102993290-e65dd800-4542-11eb-82c2-5753b8cf99ba.png)

- [x] 1. When I select the model, I then see all the model property fields similar to #11.  Unlike update, required fields should show as required because they're needed for any created instances.
![image](https://user-images.githubusercontent.com/40355220/102993318-f70e4e00-4542-11eb-86cb-1cc417c04737.png)

- [x] 1. I see the Id field,  is of text type and optional but 'sticky'
![image](https://user-images.githubusercontent.com/40355220/102993354-09888780-4543-11eb-865a-131b16254404.png)

- [x] 1. I see that when this action fires it updates the data in Applaud by using the PATCH action
- [x] 1. I see that all model properties (including the id) are available to use in later recipe actions as datapills
![image](https://user-images.githubusercontent.com/40355220/102993407-258c2900-4543-11eb-8152-8d30b5059aff.png)
- [x] 1. I see that the created date is unchanged
### Pending Items
- [ ] I see that the created and last updated by data in Applaud clearly shows it's been updated by the API and that the timestamps are correct.
- As of now last updated by is stored as Anon, there is a cloud git to track this
![image](https://user-images.githubusercontent.com/40355220/99961774-015af200-2db5-11eb-8793-cfc6765ad4d8.png)

https://github.com/ApplaudSolutions/applaud-cloud/issues/2710
